package items;

public enum ClassificationType {
    GENERAL_AND_REFERENCE,
    HARDWARE,
    COMPUTER_SYSTEMS_ORGANIZATION,
    NETWORKS,
    SOFTWARE_AND_ITS_ENGINEERING,
    THEORY_OF_COMPUTATION,
    MATHEMATICS_OF_COMPUTING,
    INFORMATION_SYSTEMS,
    SECURITY_AND_PRIVACY,
    HUMAN_CENTERED_COMPUTING,
    COMPUTING_METHODOLOGIES,
    APPLIED_COMPUTING,
    SOCIAL_AND_PROFESSIONAL_TOPICS
}
